name: iconshop
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip:
    - torch
    - torchaudio
    - torchvision
    - accelerate
    - cairosvg
    - einops
    - ipython
    - Kivy
    - matplotlib
    - moviepy
    - networkx
    - numpy
    - pandas
    - pillow
    - scikit_learn
    - scipy
    - tensorboard
    - tqdm
    - transformers
    - shapely