name: iconshop
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - cudatoolkit=12.1
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.2.1+cu121
    - torchaudio==2.2.1+cu121
    - torchvision==0.17.1+cu121
    - accelerate
    - cairosvg
    - einops
    - ipython
    - Kivy
    - matplotlib
    - moviepy
    - networkx
    - pandas
    - pillow
    - scikit_learn
    - scipy
    - tensorboard
    - tqdm
    - transformers
    - shapely
    - numpy