# Training configuration for the sketch decoder model
# note: for the time being we are going to try running on a single GPU
# to make it easier to debug compilation issues
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: NO
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
use_cpu: False
gpu_ids: "0"